version: 0.0
os: linux
files:
  - source: ./app
    destination: /home/ec2-user/app
  - source: ./scripts
    destination: /home/ec2-user/scripts
  - source: ./appspec.yml
    destination: /home/ec2-user/appspec.yml
  - source: ./app.config.js
    destination

hooks:
  ApplicationStop:
    - location: scripts/cleanup.sh
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root